apiVersion: kmm.sigs.x-k8s.io/v1beta1
kind: ModuleImagesConfig
metadata:
  name: moduleimagesconfig-sample
spec:
  images:
  - image: <kmod container image URL>
    kernelVersion: 4.18.0-372.32.1.el8_6.x86_64
  imagePullPolicy: IfNotPresent
  pushBuiltImage: false
