apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    api-approved.kubernetes.io: unapproved, testing-only
    controller-gen.kubebuilder.io/version: v0.8.0
  creationTimestamp: null
  name: preflightvalidations.kmm.sigs.k8s.io
spec:
  group: kmm.sigs.k8s.io
  names:
    kind: PreflightValidation
    listKind: PreflightValidationList
    plural: preflightvalidations
    shortNames:
    - pv
    singular: preflightvalidation
  scope: Cluster
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: PreflightValidation initiates a preflight validations for all
          SpecialResources on the current Kuberentes cluster.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: 'PreflightValidationSpec describes the desired state of the
              resource, such as the kernel version that Module CRs need to be verified
              against as well as the debug configuration of the logs More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status'
            properties:
              kernelVersion:
                description: KernelImage describes the kernel image that all Modules
                  need to be checked against.
                type: string
            required:
            - kernelVersion
            type: object
          status:
            description: 'PreflightValidationStatus is the most recently observed
              status of the PreflightValidation. It is populated by the system and
              is read-only. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status'
            properties:
              crStatuses:
                description: CRStatuses contain observations about each SpecialResource's
                  preflight upgradability validation
                items:
                  properties:
                    lastTransitionTime:
                      description: LastTransitionTime is the last time the CR status
                        transitioned from one status to another. This should be when
                        the underlying status changed.  If that is not known, then
                        using the time when the API field changed is acceptable.
                      format: date-time
                      type: string
                    name:
                      description: Name of the Module CR being checked
                      type: string
                    statusReason:
                      description: StatusReason contains a string describing the status
                        source.
                      type: string
                    verificationStage:
                      description: 'Current stage of the verification process: image
                        (image existence verification), build(build process verification)'
                      enum:
                      - Image
                      - Build
                      type: string
                    verificationStatus:
                      description: 'Status of Module CR verification: true (verified),
                        false (verification failed), error (error during verification
                        process), unknown (verification has not started yet)'
                      enum:
                      - "True"
                      - "False"
                      type: string
                  required:
                  - lastTransitionTime
                  - name
                  - verificationStage
                  - verificationStatus
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
